# Generated by Django 3.2.13 on 2023-02-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('task_id', models.IntegerField()),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.list')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64)),
                ('complete', models.BooleanField(default=False)),
                ('list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.list')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('list', 'text')},
            },
        ),
    ]
