# Generated by Django 3.2.13 on 2023-02-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='text',
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.list'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('list', 'text')},
        ),
    ]
